name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install QEMU
        run: brew install qemu
      - name: Switch to nightly build
        run: rustup override add nightly
      - name: Install xbuild
        run: cargo install cargo-xbuild
      # - name: install bootimage tool
      #   run: cargo install bootimage --version "^0.7.7"
      - name: Install rust source code to rebuild
        run: rustup component add rust-src
      - name: Install LLVM tools
        run: rustup component add llvm-tools-preview
      - name: Debug Build
        run: cargo xbuild --verbose
      - name: Release Build
        run: cargo xbuild --verbose --release
      # - name: Build bootimage
      #   run: cargo bootimage
      # - name: Run tests
      #   run: cargo xtest --verbose
