name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Switch to nightly build
        run: rustup override add nightly
      - name: Install xbuild
        run: cargo install cargo-xbuild
      - name: Install rust source code to rebuild
        run: rustup component add rust-src
      - name: Debug Build
        run: cargo xbuild --verbose
      - name: Release Build
        run: cargo xbuild --verbose --release
      # - name: Run tests
      #   run: cargo xtest --verbose
