name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Debug Build
        run: cargo build --verbose
      - name: Release Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose
